### ISSUE TITLE
bcalm with no parameters: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tseemann** [Malfoy/bcalm#1]
```
% ./bcalm
Test n:1000 k:20 m:4
GO!
importg
Segmentation fault (core dumped)

% echo $?
139
```

**Comment by Malfoy** [comment]
It should no longer occurs, you should get

usage: <input> [output.dot] [minimizer length]
Note: maximum minimizer length (minimizer length = 10) requires that you type 'ulimit -n 1100' in your shell prior to running bcalm, else the software will crash

**Comment by tseemann** [comment]
Will you be making a new Release?

I'm trying to package into Brew: https://github.com/Homebrew/homebrew-science/pull/2350

**Comment by tseemann** [comment]
My default ulimit is 1024 - does BCALM open more than 1024 files?  Is the 10 and 2^10=1024 related?

**Comment by Malfoy** [comment]
Yes, with a minimizer size of 10, bcalm will open 1024 files, plus some other as the output file.
You can reduce the minimizer size to 8 to use less than 500 open files.
I will not make a new release, I'm working on GATB/bcalm who will be the next step.
